apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
spec:
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: ajanthan/echo
        imagePullPolicy: Always
        env:
          - name: APP_VERSION
            value: 1.0.0
          - name: APP_PROFILE
            value: backend
          - name: APP_BACKEND
            value: "http://echo-backend:8080"

        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
