apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-frontend-deployment
spec:
  selector:
    matchLabels:
      app: echo-frontend
  template:
    metadata:
      labels:
        app: echo-frontend
    spec:
      containers:
      - name: echo-frontend
        image: ajanthan/echo
        imagePullPolicy: Always
        env:
          - name: APP_VERSION
            value: 1.0.0
          - name: APP_PROFILE
            value: frontend
          - name: APP_BACKEND
            value: "http://echo-backend-service:8080"
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-frontend-service
spec:
  type: ClusterIP
  selector:
    app: echo-frontend
  ports:
  - port: 8080
    targetPort: 8080
