apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-backend-v1-deployment
spec:
  selector:
    matchLabels:
      app: echo-backend
      version: v1
  template:
    metadata:
      labels:
        app: echo-backend
        version: v1
    spec:
      containers:
      - name: echo-backend
        image: ajanthan/echo
        imagePullPolicy: Always
        env:
          - name: APP_VERSION
            value: v1
          - name: APP_PROFILE
            value: backend
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-backend-service
spec:
  type: ClusterIP
  selector:
    app: echo-backend
    version: v1
  ports:
  - port: 8080
    targetPort: 8080

