apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-backend-v2-deployment
spec:
  selector:
    matchLabels:
      app: echo-backend
      version: v2
  template:
    metadata:
      labels:
        app: echo-backend
        version: v2
    spec:
      containers:
      - name: echo-backend
        image: ajanthan/echo
        imagePullPolicy: Always
        env:
          - name: APP_VERSION
            value: v2
          - name: APP_PROFILE
            value: backend
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080