apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo-frontend-vs
spec:
  hosts:
  - "echo.service.local"
  gateways:
  - echo-gw
  http:
  - match:
    - uri:
        prefix: /echo
    route:
    - destination:
        port:
          number: 8080
        host: echo-frontend-service
    corsPolicy:
      allowOrigin:
      - example.com
      allowMethods:
      - GET
      allowCredentials: false
      allowHeaders:
      - X-Foo-Bar
      maxAge: "24h"
